Repository monsieurbiz/sylius-setup, pull requests merged in 2023-09, with the labels that each got.

#9 Add use for capture function
  castor.php
Labels: Status: needs review, quick win

#11 Improving processes with composer commands
  castor.php
Labels: Status: needs review

#12 Add EOL after each line added to gitignore file
  castor.php
Labels: Status: needs review, quick win

#13 Add sitemap and gdpr plugin, and add plugin tasks
  castor/sylius.php
  clevercloud/functions.sh
  themes-examples/themes/custom/templates/bundles/SyliusShopBundle/_styles.html.twig
Labels: Status: needs review

#15 Deployment: add memory limit option in php command to avoid OOM error
  clevercloud/functions.sh
Labels: Status: needs review

#10 Avoid Github action errors for PRs based on a fork
  .github/workflows/wip.yaml
Labels: do not merge, quick win

#14 feat: Enable APCu by default on Clever Cloud
  castor/clever-cloud.php
Labels: Status: needs review, quick win
