Repository monsieurbiz/sylius-setup, pull requests merged in 2024-03, with the labels that each got.

#31 feat(http auth): Add env vars & process to update HTTP Auth
  castor/clever-cloud.php
  clevercloud/functions.sh
Labels: Priority: medium, Status: needs review, quick win

#32 Add an option to specify the plugins to be installed
  README.md
  castor/sylius.php
Labels: Status: needs review

#34 Fix setup env variable: avoid error with empty value
  castor/clever-cloud.php
  clevercloud/functions.sh
Labels: Status: needs review, quick win

#35 Allows you to modify hostname with an option
  castor/clever-cloud.php
Labels: Status: needs review, quick win
